{'message':
    {'date': 1634519159,
    'supergroup_chat_created': False,
    'new_chat_members': [], 
    'sticker': 
        {'thumb': 
            {'width': 128, 
            'file_size': 4844, 
            'height': 128, 
            'file_unique_id': 'AQADSwIAAladvQpy', 
            'file_id': 'AAMCAgADGQEAAgE1YWzIdzoYVVbWY4ED-8ywrA9VSEUAAksCAAJWnb0KYlBF0FD6cZwBAAdtAAMhBA'}, 
        'set_name': 'UtyaDuck', 
        'width': 512, 
        'file_size': 12545, 
        'is_animated': True, 
        'height': 512, 
        'file_unique_id': 'AgADSwIAAladvQo', 
        'emoji': '🧮', 
        'file_id': 'CAACAgIAAxkBAAI BNWFsyHc6GFVW1mOBA_vMsKwPVUhFAAJLAgACVp29CmJQRdBQ-nGcIQQ'}, 
    'new_chat_photo': [], 
    'caption_entities': [], 
    'channel_chat_created': False, 
    'delete_chat_photo': False, 
    'chat': 
        {'username': 'Arshamalh', 
        'type': 'private', 
        'first_name': 'Arsham', 
        'id': 462370468}, 
    'message_id': 309, 
    'group_chat_created': False, 
    'photo': [], 
    'entities': [], 
    'from': {'language_code': 'en', 'username': 'Arshamalh', 'is_bot': False, 'first_name': 'Arsham', 'id': 462370468}}, 'update_id': 809039892}
